/**
 * Writes public/sitemap.xml and public/robots.txt before the build.
 *
 * The URL list is read out of src/routes/, not typed here, so a route added
 * or renamed cannot leave the sitemap quietly stale. A route is included only
 * if it is a real public page:
 *
 *   - /admin and everything under it is out. It is a login wall.
 *   - Anything with a $param segment is out. The two that exist —
 *     /alumni/story/$code and /parents/story/$code — are personal invite
 *     links where the code in the URL is the only credential. Listing them
 *     would publish the credential.
 *   - Anything whose route file sets a robots meta is out. That covers the
 *     unlisted story forms, the /alumni/submit redirect, and the four
 *     "coming next" stubs (/news, /gallery, /scholarships, /coding), which
 *     are noindex until there is a page there to index.
 *
 * On dynamic URLs: there is no per-article route in this app. News and
 * events are rendered as lists on /news and /events from Supabase rows;
 * no /news/$slug or /events/$id exists, so there is no per-row URL for a
 * sitemap to point at. When such a route is added, extend collectRoutes —
 * the rest of this file already handles whatever it returns.
 *
 * lastmod comes from the last commit that touched the route file. It is the
 * most honest signal available at build time; a build timestamp would claim
 * every page changed on every deploy, which is worse than no lastmod at all.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

const SITE_URL = "https://alphaschools.co.tz";
const ROUTES_DIR = "src/routes";
const OUT_DIR = "public";

/** Priority and change frequency by section. Hints only; crawlers may ignore them. */
function weight(path) {
  if (path === "/") return { priority: "1.0", changefreq: "weekly" };
  if (path.startsWith("/schools/")) return { priority: "0.9", changefreq: "monthly" };
  if (["/admission", "/aviation"].includes(path)) return { priority: "0.8", changefreq: "monthly" };
  if (["/events", "/contact", "/about"].includes(path)) return { priority: "0.7", changefreq: "weekly" };
  return { priority: "0.6", changefreq: "monthly" };
}

function lastModified(file) {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cI", "--", file], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return out ? out.slice(0, 10) : undefined;
  } catch {
    return undefined; // no git history (a fresh clone, or a CI shallow checkout)
  }
}

function collectRoutes() {
  const routes = [];
  for (const name of readdirSync(ROUTES_DIR)) {
    if (!name.endsWith(".tsx")) continue;
    if (name === "__root.tsx") continue;

    const file = join(ROUTES_DIR, name);
    const source = readFileSync(file, "utf8");

    const match = source.match(/createFileRoute\(\s*["']([^"']+)["']\s*\)/);
    if (!match) continue;

    // "/alumni/" is how the router spells the index of a nested folder.
    const path = match[1] === "/" ? "/" : match[1].replace(/\/$/, "");

    if (path === "/admin" || path.startsWith("/admin/")) continue;
    if (path.includes("$")) continue;
    if (/noindex/.test(source) || /name:\s*["']robots["']/.test(source)) continue;

    routes.push({ path, lastmod: lastModified(file) });
  }
  return routes.sort((a, b) => (a.path === "/" ? -1 : b.path === "/" ? 1 : a.path.localeCompare(b.path)));
}

function sitemap(routes) {
  const urls = routes
    .map(({ path, lastmod }) => {
      const { priority, changefreq } = weight(path);
      return [
        "  <url>",
        `    <loc>${SITE_URL}${path === "/" ? "/" : path}</loc>`,
        lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
        `    <changefreq>${changefreq}</changefreq>`,
        `    <priority>${priority}</priority>`,
        "  </url>",
      ]
        .filter(Boolean)
        .join("\n");
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

const ROBOTS = `# Alpha Schools — https://alphaschools.co.tz
# Generated by scripts/generate-sitemap.mjs. Edit that, not this file.

User-agent: *
Allow: /
Disallow: /admin

Sitemap: ${SITE_URL}/sitemap.xml
`;

const routes = collectRoutes();
mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, "sitemap.xml"), sitemap(routes), "utf8");
writeFileSync(join(OUT_DIR, "robots.txt"), ROBOTS, "utf8");

console.log(`sitemap.xml: ${routes.length} public URLs`);
for (const r of routes) console.log(`  ${r.path}${r.lastmod ? `  (${r.lastmod})` : ""}`);
